Login & Registration Page #28
sliit-foss/rsvp-frontend-old pull request #49
Opened 2021-06-18 14:34 UTC by MadhushaPrasad

2021-06-18 14:51 UTC, MadhushaPrasad commented
![Screenshot (158)](https://user-images.githubusercontent.com/50085447/122579325-6c7e5580-d072-11eb-8eb9-7445f2462926.png)
![Screenshot (154)](https://user-images.githubusercontent.com/50085447/122579400-7f912580-d072-11eb-93f3-c0f1f33318de.png)
![Screenshot (159)](https://user-images.githubusercontent.com/50085447/122579476-946db900-d072-11eb-883a-b0013407d8a7.png)
![Screenshot (160)](https://user-images.githubusercontent.com/50085447/122579564-a9e2e300-d072-11eb-8655-3e48e920eec3.png)
![Screenshot (161)](https://user-images.githubusercontent.com/50085447/122579640-bbc48600-d072-11eb-961b-510b4af0978a.png)

2021-06-18 14:56 UTC, Bawanthathilan commented
@MadhushaPrasad  remove purple thunder logo and right side illustrations

2021-06-18 15:14 UTC, Bawanthathilan commented
> @MadhushaPrasad remove purple thunder logo and right side illustrations

vector - https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.vecteezy.com%2Fvector-art%2F359502-vector-purple-landscape-illustration&psig=AOvVaw3L4Mt_t8A837zoBJoaXBkd&ust=1624115504816000&source=images&cd=vfe&ved=0CAoQjRxqFwoTCIjtpvC7ofECFQAAAAAdAAAAABAJ

2021-06-18 15:14 UTC, MadhushaPrasad commented
Okay

2021-06-18 16:31 UTC, sithumonline reviewed
Remove commented code blocks and some  scss blocks look like not properly formatted 🤔

2021-06-18 16:31 UTC, sithumonline commented on src/pages/LoginPage/LoginPage.jsx
> +  < /div>*/
Please remove unwanted code blocks

2021-06-18 16:31 UTC, sithumonline commented on src/App.tsx
> +          {/*<Navbar />*/}
🐭

2021-06-18 16:31 UTC, sithumonline commented on src/App.tsx
> +          {/*<Footer />*/}
🐭

2021-06-18 16:31 UTC, sithumonline commented on src/modules/HomeModules/UpComingEvents/UpComing.scss
> +//}
🐭

2021-06-18 16:44 UTC, MadhushaPrasad commented on src/pages/LoginPage/LoginPage.jsx
> +  < /div>*/
Okay

2021-06-18 18:04 UTC, Shehanka requested changes

2021-06-18 18:04 UTC, Shehanka commented on src/modules/HomeModules/UpComingEvents/UpComing.scss
> +//}
@MadhushaPrasad remove the commented code

2021-06-19 07:22 UTC, Safnaj commented
No Need Text labels, placeholders is enough i guess for email & password.

And better to modify the vector by adding the project name as "SLIIT RSVP Portal"

@Shehanka @Bawanthathilan

2021-06-19 13:10 UTC, merged